version: '3.8'
services:
  frontend:
    container_name: AICP-admin
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
      - /app/node_modules
