export enum ExamStatusEnum {
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  WAITING_FOR_REVIEW = 'WAITING_FOR_REVIEW',
  GRADED = 'GRADED',
}

export enum LevelOfDomainEnum {
  FOUNDATION_L1_L2 = 'FOUNDATION_L1_L2',
  INTERMEDIATE_L3_L4 = 'INTERMEDIATE_L3_L4',
  ADVANCED_L5_L6 = 'ADVANCED_L5_L6',
  EXPERT_L7 = 'EXPERT_L7',
}
