export enum ExamStatusEnum {
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  WAITING_FOR_REVIEW = 'WAITING_FOR_REVIEW',
  GRADED = 'GRADED',
}

export enum SFIALevel {
  LEVEL_1_AWARENESS = 'LEVEL_1_AWARENESS',
  LEVEL_2_FOUNDATION = 'LEVEL_2_FOUNDATION',
  LEVEL_3_APPLICATION = 'LEVEL_3_APPLICATION',
  LEVEL_4_INTEGRATION = 'LEVEL_4_INTEGRATION',
  LEVEL_5_INNOVATION = 'LEVEL_5_INNOVATION',
  LEVEL_6_LEADERSHIP = 'LEVEL_6_LEADERSHIP',
  LEVEL_7_MASTERY = 'LEVEL_7_MASTERY',
}
