export const NAVIGATE_URL = {
  LANDING_PAGE: '/',
  FORBIDDEN: '/403',
  NOTFOUND: '/404',
  USERS: '/users',
  USER_UPDATE: '/users/update',
  USER_CREATE: '/users/create',
  PROFILE_UPDATE: '/profile/update',
  CHANGE_PASSWORD: '/change-password',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ACTIVATION_EXPIRED: '/activation-expired',
  SIGN_IN: '/login',
  SIGN_UP: '/register',
  SIGN_OUT: '/sign-out',
  PROFILE: '/profile',
  TEST: '/aptitude-test',
  TEST_RESULT: '/history',
  TEST_RESULT_DETAIL_EXAM: '/history/:examId',
  SCHEDULE: '/scheduler',
  INTERVIEW: '/scheduler/:examId',
  PORTFOLIO: '/portfolio',
  CAPACITY: '/capacity/:examId',
  TEST_RESULT_DETAIL: '/result',
  CAPACITY_DYNAMIC: (examId: string) => `/capacity/${examId}`,
  RESULT: '/result',
  RESULT_PORTFOLIO: '/result/portfolio',
  DETAIL_COURSE: '/course/:courseId',
  DETAIL_COURSE_DYNAMIC: (courseId: string) => `/course/${courseId}`,
  INTERVIEW_DYNAMIC: (examId: string) => `/scheduler/${examId}`,
};
