export const NAVIGATE_URL = {
  LANDING_PAGE: '/',
  FORBIDDEN: '/403',
  NOTFOUND: '/404',
  USERS: '/users',
  USER_UPDATE: '/users/update',
  USER_CREATE: '/users/create',
  PROFILE_UPDATE: '/profile/update',
  CHANGE_PASSWORD: '/profile/change-password',
  SIGN_IN: '/login',
  SIGN_UP: '/register',
  SIGN_OUT: '/sign-out',
  PROFILE: '/profile',
  TEST: '/aptitude-test',
  TEST_RESULT: '/history',
  MENTOR_ACTIVATION: 'mentor-activation/:token',
};
