export const QUERY_KEY = {
  PERMISSIONS: 'PERMISSIONS',
  ROLES: 'ROLES',
  USERS: 'USERS',
  PROFILE: 'PROFILE',
  EXAM_HISTORY: 'EXAM_HISTORY',
};

export const REACT_QUERY = {
  REQUEST_CACHE_TIME: 10 * 60 * 1000, // 10m
  REQUEST_STALE_TIME: 10 * 60 * 1000, // 10m
};

export const REQUEST_DEBOUNCE_DEFAULT_TIME = 1000;
