export const QUERY_KEY = {
  PERMISSIONS: 'PERMISSIONS',
  ROLES: 'ROLES',
  USERS: 'USERS',
  PROFILE: 'PROFILE',
  EXAM_HISTORY: 'EXAM_HISTORY',
  HAS_TAKEN_EXAM: 'TAKEN_EXAM',
  HAS_TAKEN_EXAM_DEFAULT: 'TAKEN_EXAM_DEFAULT',
  EXAM_SETS: 'EXAM_SETS',
  EXAM_DETAIL: 'EXAM_DETAIL',
};

export const REACT_QUERY = {
  REQUEST_CACHE_TIME: 10 * 60 * 1000, // 10m
  REQUEST_STALE_TIME: 10 * 60 * 1000, // 10m
};

export const REQUEST_DEBOUNCE_DEFAULT_TIME = 1000;
