export const QUERY_KEY = {
  PERMISSIONS: 'PERMISSIONS',
  ROLES: 'ROLES',
  USERS: 'USERS',
  PROFILE: 'PROFILE',
  HAS_TAKEN_EXAM: 'TAKEN_EXAM',
  HAS_TAKEN_EXAM_DEFAULT: 'TAKEN_EXAM_DEFAULT',
  EXAM_SETS: 'EXAM_SETS',
  PORTFOLIO: 'PORTFOLIO',
  EXAM_HISTORY: 'EXAM_HISTORY',
  DATA_CARD: 'DATA_CARD',
  DATA_CHART: 'DATA_CHART',
  JOB: 'JOB',
  EXAM_DETAIL: 'EXAM_DETAIL',
  CHECK_RESET_PASSWORD_TOKEN: 'CHECK_RESET_PASSWORD_TOKEN',
  EXAM_RESULT: 'EXAM_RESULT',
  ZALO_OTP: 'ZALO_OTP',
  ZALO_OTP_SEND_OTP: 'ZALO_OTP_SEND_OTP',
  ZALO_OTP_VERIFY: 'ZALO_OTP_VERIFY',
  ZALO_OTP_CHECK_STATUS: 'ZALO_OTP_CHECK_STATUS',
  ZALO_OTP_COUNTRY_CODE: 'ZALO_OTP_COUNTRY_CODE',
  ZALO_OTP_CAN_SEND: 'ZALO_OTP_CAN_SEND',
  CHECK_MY_INTERVIEW: 'CHECK_MY_INTERVIEW',
  SLOT_INTERVIEW: 'SLOT_INTERVIEW',
};

export const REACT_QUERY = {
  REQUEST_CACHE_TIME: 10 * 60 * 1000, // 10m
  REQUEST_STALE_TIME: 10 * 60 * 1000, // 10m
};

export const REQUEST_DEBOUNCE_DEFAULT_TIME = 1000;
