export const API_URL = {
  PERMISSION_PARENT: '/permissions/parents',
  PERMISSION_TREE: '/permissions/all',
  PERMISSIONS: '/permissions',
  PERMISSION: '/permission',
  ROLES: '/roles',
  USERS: '/users',
  CLASSES: '/classes',
  ASSIGN_PERMISSION: '/users/assign-permission',
  LOGIN: '/auth/login',
  REFRESH_TOKEN: '/auth/refresh',
  GET_PROFILE: '/users/me',
  UPDATE_PROFILE: '/users/profile',
  UPLOAD_AVATAR: '/users/avatar',
  REMOVE_AVATAR: '/users/avatar',
  ALL_ROLES: '/roles/all',
  CHANGE_PASSWORD: '/users/change-password',
  RESET_PASSWORD: 'users/reset-password',
  FORGOT_PASSWORD: 'users/forgot-password',
  UPDATE_FORGOT_PASSWORD: 'users/update-forgot-password',
  LOGOUT: '/auth/logout',
  REGISTER_USER: '/auth/register',
  ACTIVATE_ACCOUNT: '/auth/activate',
  CHECK_TAKEN_EXAM: '/exam/has-taken-exam',
  CHECK_TAKEN_EXAM_DEFAULT: '/exam/taken-input-test',
  EXAM_SETS_INPUT_TEST: '/exam-sets/input-test',
  ANSWERS: '/answers',
  HISTORY_TESTING: '/exam/history-exam/',
};

export const VEHICLES_URL = '/vehicles';
