export const API_URL = {
  USERS: '/users',
  LOGIN: '/auth/login',
  LOGIN_WITH_GOOGLE: '/auth/login-google',
  REFRESH_TOKEN: '/auth/refresh',
  GET_PROFILE: '/users/me',
  UPDATE_PROFILE: '/users/profile',
  UPLOAD_AVATAR: '/users/avatar',
  CHANGE_PASSWORD: '/users/change-password',
  RESET_PASSWORD: 'users/reset-password',
  CHECK_RESET_TOKEN: 'users/check-reset-token',
  FORGOT_PASSWORD: 'users/forgot-password',
  UPDATE_FORGOT_PASSWORD: 'users/update-forgot-password',
  LOGOUT: '/auth/logout',
  REGISTER_USER: '/auth/register',
  HISTORY_TESTING: '/exam/history-exam/',
  ACTIVATE_ACCOUNT: '/auth/activate',
  CHECK_TAKEN_EXAM: '/exam/has-taken-exam',
  CHECK_TAKEN_EXAM_DEFAULT: '/exam/taken-input-test',
  EXAM_SETS_INPUT_TEST: '/exam-sets/input-test',
  ANSWERS: '/answers',
  MENTORS_AVAILABLE: '/mentors/available',
  PORTFOLIO: '/users/portfolio',
  PORTFOLIO_DOWNLOAD: '/users/portfolio/download',
  GET_JOB: 'domain/names',
  DETAIL_EXAM: '/exam',
};
